version: "3.4"
services:
    webserver:
        image: django-docker-demo:webserver
        ports:
            - 80:80
    django:
        image: django-docker-demo:latest
        environment:
            DJANGO_DEBUG: "false"
            DJANGO_SECRET_KEY: "AVhqJxkBn5cSS7Zp4jqWAMMAOXRoKfuOHduKVFUo"
            DJANGO_DB_HOST: "db"
            DJANGO_DB_DATABASE: "djangoqa"
            DJANGO_DB_USER: "djangouser"
            DJANGO_DB_PASSWORD: "djangouserpassword"
    celery-worker:
        image: django-docker-demo:latest
        command: "celery -A django_demo.tasks worker --loglevel=info"
    redis:
        image: redis:5.0-alpine
    db:
        image: mariadb:10.4
        restart: always
        environment:
            MYSQL_DATABASE: "djangoqa"
            MYSQL_USER: "djangouser"
            MYSQL_PASSWORD: "djangouserpassword"
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        volumes:
            - django-db-qa:/var/lib/mysql

volumes:
    django-db-qa: