version: "3.4"
services:
    webserver:
        image: django-docker-demo:webserver
        build:
            dockerfile: Dockerfile
            target: webserver
            context: .
        ports:
            - 8080:80
        logging: { options: { max-size: "10m", max-file: "3" } }
    django:
        image: django-docker-demo:dev
        build:
            dockerfile: Dockerfile
            target: dev
            context: .
        ports:
            - 8000:8000
            - 5678:5678
        volumes:
            - ./django_demo/:/app/
        environment:
            DJANGO_DEBUG: "y"
            DJANGO_DB_HOST: "db"
            DJANGO_DB_DATABASE: "django"
            DJANGO_DB_USER: "djangouser"
            DJANGO_DB_PASSWORD: "djangouserpassword"
        logging: { options: { max-size: "10m", max-file: "3" } }

    celery-worker:
        image: django-docker-demo:latest
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - ./django_demo/:/app/
        command: "celery -A django_demo.tasks worker --loglevel=info"
        logging: { options: { max-size: "10m", max-file: "3" } }

    redis:
        image: redis:5.0-alpine
        logging: { options: { max-size: "10m", max-file: "3" } }
    
    db:
        image: mariadb:10.4
        restart: always
        environment:
            MYSQL_DATABASE: "django"
            MYSQL_USER: "djangouser"
            MYSQL_PASSWORD: "djangouserpassword"
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        volumes:
            - django-db:/var/lib/mysql
        logging: { options: { max-size: "10m", max-file: "3" } }

volumes:
    django-db: